addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.6")
addSbtPlugin("org.lyranthe.sbt"          % "partial-unification" % "1.1.2")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"     % "0.3.0")
addSbtPlugin("com.47deg"                 % "sbt-org-policies"    % "0.11.3")
addSbtPlugin("com.47deg"                 % "sbt-microsites"      % "0.9.7")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.4.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.21")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.9.0")
