addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.11")
addSbtPlugin("org.lyranthe.sbt"          % "partial-unification" % "1.1.2")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"     % "0.7.0")
addSbtPlugin("com.47deg"                 % "sbt-org-policies"    % "0.13.1")
addSbtPlugin("com.47deg"                 % "sbt-microsites"      % "1.1.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.6.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.9.0")
